import { FaBoxes, FaChalkboardTeacher } from "react-icons/fa";

import {
  FaBuilding,
  FaCity,
  FaIndustry,
  FaScrewdriverWrench,
  FaHammer,
  FaWrench,
  FaGear,
  FaGears,
  FaHelmetSafety,
  FaUsers,
  FaUserTie,
  FaUserGear,
  FaUserShield,
  FaUserCheck,
  FaDiagramProject,
  FaListCheck,
  FaClipboardCheck,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaSignal,
  FaBolt,
  FaLightbulb,
  FaRocket,
  FaAward,
  FaStar,
  FaMedal,
  FaCertificate,
  FaShield,
  FaLock,
  FaUnlock,
  FaKey,
  FaFingerprint,
  FaDatabase,
  FaServer,
  FaCloud,
  FaNetworkWired,
  FaWifi,
  FaLaptop,
  FaDesktop,
  FaMobileScreen,
  FaMicrochip,
  FaRobot,
  FaCode,
  FaTerminal,
  FaBug,
  FaMagnifyingGlass,
  FaEye,
  FaCamera,
  FaVideo,
  FaImage,
  FaGlobe,
  FaMap,
  FaLocationDot,
  FaCompass,
  FaRoad,
  FaTruck,
  FaTruckFast,
  FaWarehouse,
  FaBoxOpen,
  FaRecycle,
  FaLeaf,
  FaSeedling,
  FaTree,
  FaWater,
  FaFire,
  FaSolarPanel,
  FaWind,
  FaBatteryFull,
  FaPlug,
  FaHandshake,
  FaBriefcase,
  FaBusinessTime,
  FaMoneyBillWave,
  FaCoins,
  FaWallet,
  FaCreditCard,
  FaFile,
  FaFileContract,
  FaFileInvoice,
  FaBook,
  FaGraduationCap,
  FaSchool,
  FaHeadset,
  FaPhone,
  FaEnvelope,
  FaComments,
  FaBullhorn,
  FaCalendar,
  FaClock,
  FaCircleCheck,
  FaThumbsUp,
  FaGem,
  FaInfinity,
} from "react-icons/fa6";

export const FEATURE_ICONS = [
  "building",
  "city",
  "industry",

  "screwdriver_wrench",
  "hammer",
  "wrench",
  "gear",
  "gears",

  "helmet_safety",

  "users",
  "user_tie",
  "user_gear",
  "user_shield",
  "user_check",

  "diagram_project",
  "list_check",
  "clipboard_check",

  "chart_bar",
  "chart_line",
  "chart_pie",
  "signal",

  "bolt",
  "lightbulb",
  "rocket",
  "award",
  "star",
  "medal",
  "certificate",

  "shield",
  "lock",
  "unlock",
  "key",
  "fingerprint",

  "database",
  "server",
  "cloud",
  "network_wired",
  "wifi",

  "laptop",
  "desktop",
  "mobile_screen",
  "microchip",
  "robot",
  "code",
  "terminal",
  "bug",
  "magnifying_glass",
  "eye",

  "camera",
  "video",
  "image",
  "globe",

  "map",
  "location_dot",
  "compass",
  "road",

  "truck",
  "truck_fast",
  "warehouse",
  "boxes",
  "box_open",
  "recycle",

  "leaf",
  "seedling",
  "tree",
  "water",
  "fire",

  "solar_panel",
  "wind",
  "battery_full",
  "plug",

  "handshake",
  "briefcase",
  "business_time",

  "money_bill_wave",
  "coins",
  "wallet",
  "credit_card",

  "file",
  "file_contract",
  "file_invoice",
  "book",
  "graduation_cap",
  "school",
  "chalkboard_teacher",

  "headset",
  "phone",
  "envelope",
  "comments",
  "bullhorn",

  "calendar",
  "clock",

  "circle_check",
  "thumbs_up",

  "gem",
  "infinity"
] as const;

export const FEATURE_ICONS_MAP = {
  default: FaBuilding,

  building: FaBuilding,
  city: FaCity,
  industry: FaIndustry,

  screwdriver_wrench: FaScrewdriverWrench,
  hammer: FaHammer,
  wrench: FaWrench,
  gear: FaGear,
  gears: FaGears,

  helmet_safety: FaHelmetSafety,

  users: FaUsers,
  user_tie: FaUserTie,
  user_gear: FaUserGear,
  user_shield: FaUserShield,
  user_check: FaUserCheck,

  diagram_project: FaDiagramProject,
  list_check: FaListCheck,
  clipboard_check: FaClipboardCheck,

  chart_bar: FaChartBar,
  chart_line: FaChartLine,
  chart_pie: FaChartPie,
  signal: FaSignal,

  bolt: FaBolt,
  lightbulb: FaLightbulb,
  rocket: FaRocket,
  award: FaAward,
  star: FaStar,
  medal: FaMedal,
  certificate: FaCertificate,

  shield: FaShield,
  lock: FaLock,
  unlock: FaUnlock,
  key: FaKey,
  fingerprint: FaFingerprint,

  database: FaDatabase,
  server: FaServer,
  cloud: FaCloud,
  network_wired: FaNetworkWired,
  wifi: FaWifi,

  laptop: FaLaptop,
  desktop: FaDesktop,
  mobile_screen: FaMobileScreen,
  microchip: FaMicrochip,
  robot: FaRobot,
  code: FaCode,
  terminal: FaTerminal,
  bug: FaBug,
  magnifying_glass: FaMagnifyingGlass,
  eye: FaEye,

  camera: FaCamera,
  video: FaVideo,
  image: FaImage,
  globe: FaGlobe,

  map: FaMap,
  location_dot: FaLocationDot,
  compass: FaCompass,
  road: FaRoad,

  truck: FaTruck,
  truck_fast: FaTruckFast,
  warehouse: FaWarehouse,
  boxes: FaBoxes,
  box_open: FaBoxOpen,
  recycle: FaRecycle,

  leaf: FaLeaf,
  seedling: FaSeedling,
  tree: FaTree,
  water: FaWater,
  fire: FaFire,

  solar_panel: FaSolarPanel,
  wind: FaWind,
  battery_full: FaBatteryFull,
  plug: FaPlug,

  handshake: FaHandshake,
  briefcase: FaBriefcase,
  business_time: FaBusinessTime,

  money_bill_wave: FaMoneyBillWave,
  coins: FaCoins,
  wallet: FaWallet,
  credit_card: FaCreditCard,

  file: FaFile,
  file_contract: FaFileContract,
  file_invoice: FaFileInvoice,
  book: FaBook,
  graduation_cap: FaGraduationCap,
  school: FaSchool,
  chalkboard_teacher: FaChalkboardTeacher,

  headset: FaHeadset,
  phone: FaPhone,
  envelope: FaEnvelope,
  comments: FaComments,
  bullhorn: FaBullhorn,

  calendar: FaCalendar,
  clock: FaClock,

  circle_check: FaCircleCheck,
  thumbs_up: FaThumbsUp,

  gem: FaGem,
  infinity: FaInfinity,
} as const;